//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TilausDbApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kayttajat
    {
        public int Id { get; set; }
        public string KayttajaNimi { get; set; }
        public string Salasana { get; set; }
    }
}
